CREATE TABLE reconfile (
    PartnerId UUID,
    PartnerName VARCHAR,
    CustomerId VARCHAR,
    CustomerName VARCHAR,
    CustomerDomainName VARCHAR,
    CustomerCountry VARCHAR,
    MpnId INTEGER,
    Tier2MpnId INTEGER,
    InvoiceNumber VARCHAR,
    ProductId VARCHAR,
    SkuId VARCHAR,
    AvaliabilityId VARCHAR,
    SkuName VARCHAR,
    ProductName VARCHAR,
    PublisherName VARCHAR,
    PublisherId VARCHAR,
    SubscriptionDescription VARCHAR,
    SubscriptionId VARCHAR,
    ChargeStartDate TIMESTAMP,
    ChargeEndDate TIMESTAMP,
    UsageDate TIMESTAMP,
    MeterType VARCHAR,
    MeterCategory VARCHAR,
    MeterId VARCHAR,
    MeterSubCategory VARCHAR,
    MeterName VARCHAR,
    MeterRegion VARCHAR,
    Unit VARCHAR,
    ResourceLocation VARCHAR,
    ConsumedService VARCHAR,
    ResourceGroup VARCHAR,
    ResourceURI VARCHAR,
    ChargeType VARCHAR,
    UnitPrice FLOAT,
    Quantity FLOAT,
    UnitType VARCHAR,
    BillingPreTaxTotal FLOAT,
    BillingCurrency VARCHAR,
    PricingPreTaxTotal FLOAT,
    PricingCurrency VARCHAR,
    ServiceInfo1 VARCHAR,
    ServiceInfo2 VARCHAR,
    Tags VARCHAR,
    AdditionalInfo VARCHAR,
    EffectiveUnitPrice FLOAT,
    PCToBCExchangeRate NUMERIC,
    PCToBCExchangeRateDate TIMESTAMP,
    EntitlementId VARCHAR,
    EntitlementDescription VARCHAR,
    PartnerEarnedCreditPercentage NUMERIC,
    CreditPercentage NUMERIC,
    CreditType VARCHAR,
    BenefitOrderId VARCHAR,
    BenefitId VARCHAR,
    BenefitType VARCHAR
);

CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    name VARCHAR NOT NULL,
    email VARCHAR UNIQUE NOT NULL,
    password VARCHAR NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);